config/routes.rb
Rails.application.routes.draw do
  resources :municipes, except: [:show, :destroy]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Defines the root path route ("/")
  root 'municipes#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/endereco.rb
class Endereco < ApplicationRecord
  before_validation :normalize_cep
  before_validation :normalize_uf

  belongs_to :municipe

  validates :cep, presence: true, length: { is: 8 }
  validates :numero, presence: true
  validates :logradouro, presence: true
  validates :bairro, presence: true
  validates :cidade, presence: true
  validates :uf, presence: true, length: { is: 2 }

  def self.searchable_attributes
    ['bairro', 'cep', 'cidade', 'codigo_ibge', 'complemento', 'logradouro', 'numero', 'uf']
  end

  def formatted
    "#{logradouro} #{numero}#{complemento.present? ? " #{complemento}" : ''}, #{bairro}, #{cidade}-#{uf}"
  end

  private

  def normalize_cep
    self.cep = cep.try(:gsub, /[^0-9]/, '')
  end

  def normalize_uf
    self.uf = uf.try(:upcase)
  end
end

app/models/municipe.rb
class Municipe < ApplicationRecord
  before_save :normalize_telefone, :normalize_cpf, :normalize_cns
  after_create :notify_new_registration
  after_update :notify_updated_status, if: :status_changed?

  has_one :endereco, dependent: :destroy, required: true, inverse_of: :municipe
  has_one_attached :foto do |img|
    img.variant :thumb, resize_to_limit: [100, 100]
  end

  accepts_nested_attributes_for :endereco

  validates :nome, com_sobrenome: { message: 'deve ter um sobrenome' }
  validates :cpf, cpf: true, uniqueness: true
  validates :cns, cns: true, uniqueness: true
  validates :email, email: { mode: :strict }
  validates :data_nascimento, presence: true, reasonable_age: true, birthday_in_the_past: true
  validates :telefone, phone: true
  validates :ativo, inclusion: [true, false]
  validates :foto, presence: true

  scope :ativos, -> { where(ativo: true) }
  scope :inativos, -> { where(ativo: false) }

  def self.searchable_attributes
    ['nome', 'cpf', 'cns', 'email', 'telefone']
  end

  def self.search(query, ativos_param = nil)
    search_result = filter_ativos_search(ativos_param)
    return search_result.includes(:endereco) if query.blank?

    municipe_conditions = searchable_attributes.map { |attribute| "#{attribute} ILIKE :query" }
    endereco_conditions = Endereco.searchable_attributes.map { |attribute| "enderecos.#{attribute} ILIKE :query" }
    conditions = municipe_conditions.concat(endereco_conditions).join(' OR ')
    search_result.joins(:endereco).includes(:endereco).where(conditions, query: "%#{query.strip}%")
  end

  def self.filter_ativos_search(param)
    return ativos if param == 'ativos'
    return inativos if param == 'inativos'

    unscoped
  end

  def formatted_endereco
    endereco.formatted
  end

  private

  def normalize_telefone
    self.telefone = Phonelib.parse(telefone).full_e164.presence
  end

  def normalize_cpf
    cpf.gsub(/[^\d]/, '')
  end

  def normalize_cns
    cpf.gsub(/[^\d]/, '')
  end

  def status_changed?
    saved_changes.key?(:ativo)
  end

  def notify_new_registration
    send_new_registration_email
    send_new_registration_sms
  end

  def notify_updated_status
    send_status_updated_email
    send_status_updated_sms
  end

  def send_new_registration_email
    MunicipeMailer.with(municipe: self).new_registration.deliver_later
  end

  def send_status_updated_email
    MunicipeMailer.with(municipe: self, saved_changes: saved_changes[:ativo]).status_updated.deliver_later
  end

  def send_new_registration_sms
    SendSmsJob.perform_later(id, 'Suas informações foram cadastradas na plataforma Municipe CRUD.')
  end

  def send_status_updated_sms
    action = ativo? ? 'ativado' : 'desativado'
    SendSmsJob.perform_later(id, "Seu cadastro foi #{action} na plataforma Municipe CRUD.")
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/municipes_controller.rb
class MunicipesController < ApplicationController
  before_action :set_municipe, only: [:edit, :update]

  # GET /municipes or /municipes.json
  def index
    @municipes = Municipe.search(params[:query], params[:ativos]).with_attached_foto.page(params[:page])
  end

  # GET /municipes/new
  def new
    @municipe = Municipe.new
    @municipe.build_endereco
  end

  # GET /municipes/1/edit
  def edit; end

  # POST /municipes or /municipes.json
  def create
    @municipe = Municipe.new(municipe_params)

    respond_to do |format|
      if @municipe.save
        format.html { redirect_to municipes_url, notice: 'Munícipe cadastrado com sucesso' }
        format.json { render :show, status: :created, location: @municipe }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @municipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /municipes/1 or /municipes/1.json
  def update
    respond_to do |format|
      if @municipe.update(municipe_params)
        format.html { redirect_to municipes_url, notice: 'Munícipe atualizado com sucesso' }
        format.json { render :show, status: :ok, location: @municipe }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @municipe.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_municipe
    @municipe = Municipe.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def municipe_params
    params.require(:municipe).permit(:nome, :cpf, :cns, :email, :data_nascimento, :telefone, :ativo, :foto,
                                     endereco_attributes: [:cep, :logradouro, :numero, :complemento, :bairro, :cidade,
                                                           :uf, :codigo_ibge])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/municipes_helper.rb
module MunicipesHelper
  def municipe_ativo(municipe)
    municipe.ativo? ? 'ativo' : 'inativo'
  end

  def data_nascimento(municipe)
    municipe.data_nascimento.strftime('%d/%m/%Y')
  end

  def radio_ativos_checked?(radio, param)
    radio == param || (radio == 'todos' && param.blank?)
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MunicipesCrud</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/municipes/_form.html.erb
<%= form_with(model: municipe) do |form| %>
  <% if municipe.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(municipe.errors.count, "error") %> prohibited this municipe from being saved:</h2>

      <ul>
        <% municipe.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-check">
    <%= form.check_box :ativo, class: "form-check-input" %>
    <%= form.label :ativo, 'Ativo?', class: 'form-check-label' %>
  </div>

  <div class="form-group">
    <%= form.label :nome %>
    <%= form.text_field :nome, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :cpf, 'CPF' %>
    <%= form.text_field :cpf, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :cns, 'CNS' %>
    <%= form.text_field :cns, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :email %>
    <%= form.text_field :email, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :data_nascimento %>
    <%= form.date_field :data_nascimento, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :telefone %>
    <%= form.text_field :telefone, class: "form-control" %>
  </div>

  <div class="custom-file">
    <%= form.label :foto, class: "custom-file-label" %>
    <%= form.file_field :foto, class: "custom-file-input" %>
  </div>

  <h3 class="mt-5">Endereço</h3>

  <%= form.fields_for(:endereco) do |form_endereco| %>
    <div class="form-group">
      <%= form_endereco.label :cep %>
      <%= form_endereco.text_field :cep, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= form_endereco.label :logradouro %>
      <%= form_endereco.text_field :logradouro, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= form_endereco.label :numero %>
      <%= form_endereco.text_field :numero, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= form_endereco.label :complemento %>
      <%= form_endereco.text_field :complemento, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= form_endereco.label :bairro %>
      <%= form_endereco.text_field :bairro, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= form_endereco.label :cidade %>
      <%= form_endereco.text_field :cidade, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= form_endereco.label :uf %>
      <%= form_endereco.text_field :uf, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= form_endereco.label :codigo_ibge %>
      <%= form_endereco.text_field :codigo_ibge, class: "form-control" %>
    </div>
  <% end %>

  <div class="mt-3">
    <%= button_tag 'Salvar', type: :submit, class: 'btn btn-primary' %>
    <%= link_to 'Cancelar', municipes_path, class: 'btn btn-light' %>
  </div>
<% end %>

app/views/municipes/_municipe.html.erb
<div id="<%= dom_id municipe %>">
  <p>
    <strong>Nome:</strong>
    <%= municipe.nome %>
  </p>

  <p>
    <strong>Cpf:</strong>
    <%= municipe.cpf %>
  </p>

  <p>
    <strong>Cns:</strong>
    <%= municipe.cns %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= municipe.email %>
  </p>

  <p>
    <strong>Data nascimento:</strong>
    <%= municipe.data_nascimento %>
  </p>

  <p>
    <strong>Telefone:</strong>
    <%= municipe.telefone %>
  </p>

  <p>
    <strong>Ativo:</strong>
    <%= municipe.ativo %>
  </p>

</div>

app/views/municipes/edit.html.erb
<h1>Editar Munícipe</h1>

<%= render "form", municipe: @municipe %>

app/views/municipes/index.html.erb
<p style="color: green"><%= notice %></p>

<div class="row">
  <div class="col-md">
    <div>
      <h1>Munícipes</h1>
    </div>
  </div>
  <div class="col-md">
    <%= link_to 'Cadastrar munícipe', new_municipe_path, class: 'btn btn-primary float-md-end' %>
  </div>
</div>

<hr>

<div id="search-form" class="mt-md-3 mt-sm-5">
  <%= form_tag municipes_path, method: :get, data: { controller: 'search-form' } do %>
    <div class="row">
      <div class="col-md-3">
        <%= search_field_tag :query, params[:query], class: 'form-control', placeholder: 'Buscar munícipes...', data: { action: 'search->search-form#submit' } %>
      </div>
      <div class="col-md-3">
        <div class="form-check form-check-inline">
          <%= radio_button_tag :ativos, 'ativos', radio_ativos_checked?('ativos', params[:ativos]), class: 'form-check-input', id: 'ativos_ativos', data: { action: 'change->search-form#submit' } %>
          <%= label_tag :ativos, 'ativos', class: 'form-check-label', for: 'ativos_ativos' %>
        </div>
        <div class="form-check form-check-inline">
          <%= radio_button_tag :ativos, 'inativos', radio_ativos_checked?('inativos', params[:ativos]), class: 'form-check-input', id: 'ativos_inativos', data: { action: 'change->search-form#submit' } %>
          <%= label_tag :ativos, 'inativos', class: 'form-check-label', for: 'ativos_inativos' %>
        </div>
        <div class="form-check form-check-inline">
          <%= radio_button_tag :ativos, 'todos', radio_ativos_checked?('todos', params[:ativos]), class: 'form-check-input', id: 'ativos_todos', data: { action: 'change->search-form#submit' } %>
          <%= label_tag :ativos, 'todos', class: 'form-check-label', for: 'ativos_todos' %>
        </div>
      </div>
      <div class="col-md">
        <%= button_tag 'Buscar', type: :submit, class: 'btn btn-primary float-md-start' %>
      </div>
    </div>
  <% end %>
</div>

<div id="municipes" class="mt-md-3 mt-sm-5">
  <table class="table">
    <thead>
      <tr>
        <th scope="col"></th>
        <th scope="col">Status</th>
        <th scope="col">Nome</th>
        <th scope="col">CPF</th>
        <th scope="col">CNS</th>
        <th scope="col">Email</th>
        <th scope="col">Nascimento</th>
        <th scope="col">Telefone</th>
        <th scope="col">Endereço</th>
        <th scope="col"></th>
      </tr>
    </thead>
    <tbody>
      <% @municipes.each do |municipe| %>
        <tr>
          <td scope="row"><%= image_tag municipe.foto.variant(resize_to_limit: [50, 50]) %></td>
          <td><%= municipe_ativo(municipe) %></td>
          <td><%= municipe.nome %></td>
          <td><%= municipe.cpf %></td>
          <td><%= municipe.cns %></td>
          <td><%= municipe.email %></td>
          <td><%= data_nascimento(municipe) %></td>
          <td><%= municipe.telefone %></td>
          <td><%= municipe.formatted_endereco %></td>
          <td><%= link_to 'Editar', edit_municipe_path(municipe) %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<div id="pagination">
  <%= paginate @municipes %>
</div>

app/views/municipes/new.html.erb
<h1>Cadastrar Munícipe</h1>

<%= render "form", municipe: @municipe %>